import type { Request, Response } from 'express';

/** Machine-readable route map for API consumers (e.g. mobile). GET /api/docs */
export const ROUTES = [
  { method: 'GET', path: '/api/health', auth: false, description: 'Health check' },
  { method: 'GET', path: '/api/v1', auth: false, description: 'API v1 welcome' },
  { method: 'POST', path: '/api/v1/auth/admin/login', auth: false, description: 'Admin login (sets cookies)' },
  { method: 'POST', path: '/api/v1/auth/admin/refresh', auth: false, description: 'Admin refresh (cookie)' },
  { method: 'POST', path: '/api/v1/auth/admin/logout', auth: true, description: 'Admin logout' },
  { method: 'POST', path: '/api/v1/auth/customer/send-otp', auth: false, description: 'Customer: send phone OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/customer/verify-otp', auth: false, description: 'Customer: verify OTP (body: phone, otp); returns user, accessToken, refreshToken, expiresIn' },
  { method: 'POST', path: '/api/v1/auth/customer/resend-otp', auth: false, description: 'Customer: resend OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/customer/refresh', auth: false, description: 'Customer: refresh tokens (body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/customer/logout', auth: true, description: 'Customer: logout (optional body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/vendor/send-otp', auth: false, description: 'Vendor: send OTP to phone (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/vendor/verify-otp', auth: false, description: 'Vendor: verify OTP (body: phone, otp); returns accessToken, refreshToken, isNewVendor, onboardingStep' },
  { method: 'POST', path: '/api/v1/auth/vendor/resend-otp', auth: false, description: 'Vendor: resend OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/vendor/refresh', auth: false, description: 'Vendor: refresh tokens (body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/vendor/logout', auth: true, description: 'Vendor: logout (Bearer required; optional body: refreshToken, fcmToken)' },
  { method: 'GET', path: '/api/v1/vendor/onboarding/status', auth: true, description: 'Vendor onboarding: get status (onboardingStep, approvalStatus, submittedAt, name)' },
  { method: 'PATCH', path: '/api/v1/vendor/onboarding/business-info', auth: true, description: 'Vendor onboarding Step 2: business info (multipart: storeName, description, operatingHours JSON, logo)' },
  { method: 'PATCH', path: '/api/v1/vendor/onboarding/address', auth: true, description: 'Vendor onboarding Step 3: address (addressLine1, addressLine2, landmark, lat, lng, addressLabel)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/kyc-documents', auth: true, description: 'Vendor onboarding Step 5: KYC (multipart: businessRegistration, identityDocument, healthSafetyLicense optional)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/submit', auth: true, description: 'Vendor onboarding Step 6: submit application (422 if steps incomplete)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/resubmit', auth: true, description: 'Vendor onboarding: resubmit after rejection; resets approvalStatus=none, step=4, emits vendor:new_submission' },
  { method: 'GET', path: '/api/v1/admin/users', auth: true, description: 'List users (admin)' },
  { method: 'POST', path: '/api/v1/admin/users', auth: true, description: 'Create user (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/export/csv', auth: true, description: 'Export users CSV (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/:id', auth: true, description: 'Get user (admin)' },
  { method: 'PUT', path: '/api/v1/admin/users/:id', auth: true, description: 'Update user (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/users/:id', auth: true, description: 'Delete user (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/users/:id/status', auth: true, description: 'Patch user status (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/:id/orders', auth: true, description: 'Get user orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/customers', auth: true, description: 'List customers (admin)' },
  { method: 'GET', path: '/api/v1/admin/customers/:id', auth: true, description: 'Get customer (admin)' },
  { method: 'POST', path: '/api/v1/admin/customers', auth: true, description: 'Create customer (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/customers/:id', auth: true, description: 'Update customer (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/customers/:id/block', auth: true, description: 'Block/unblock customer (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/customers/:id', auth: true, description: 'Delete customer (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/stats/pending-count', auth: true, description: 'Pending drivers count (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers', auth: true, description: 'List drivers (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Get driver (admin)' },
  { method: 'PUT', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Update driver (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Delete driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/approve', auth: true, description: 'Approve driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/reject', auth: true, description: 'Reject driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/status', auth: true, description: 'Update driver status (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id/orders', auth: true, description: 'Driver orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id/location', auth: true, description: 'Driver location (admin)' },
  { method: 'GET', path: '/api/v1/admin/orders/stats/summary', auth: true, description: 'Orders stats summary (admin)' },
  { method: 'GET', path: '/api/v1/admin/orders', auth: true, description: 'List orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/orders/:id', auth: true, description: 'Get order (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/status', auth: true, description: 'Update order status (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/cancel', auth: true, description: 'Cancel order (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/assign-driver', auth: true, description: 'Assign driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/driver', auth: true, description: 'Assign driver (admin); body: driverId' },
  { method: 'GET', path: '/api/v1/admin/transactions/stats/revenue', auth: true, description: 'Revenue stats (admin)' },
  { method: 'GET', path: '/api/v1/admin/transactions', auth: true, description: 'List transactions (admin)' },
  { method: 'GET', path: '/api/v1/admin/transactions/:id', auth: true, description: 'Get transaction (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors', auth: true, description: 'List vendors (admin); query: approvalStatus, search, status; response meta: pendingCount' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Get vendor (admin)' },
  { method: 'POST', path: '/api/v1/admin/vendors', auth: true, description: 'Create vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Update vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/block', auth: true, description: 'Block/unblock vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/approve', auth: true, description: 'Approve vendor (admin); vendor must be pending; emits vendor:approved, FCM to vendor' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/reject', auth: true, description: 'Reject vendor (admin); body: { reason } min 10 chars; emits vendor:rejected, FCM to vendor' },
  { method: 'DELETE', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Delete vendor (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id/menu-items', auth: true, description: 'List vendor menu items (admin)' },
  { method: 'POST', path: '/api/v1/admin/vendors/:id/menu-items', auth: true, description: 'Create menu item (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/menu-items/:itemId', auth: true, description: 'Update menu item (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/vendors/:id/menu-items/:itemId', auth: true, description: 'Delete menu item (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id/products', auth: true, description: 'List vendor products (admin, Phase 4); query: page, limit, category, isAvailable' },
  { method: 'GET', path: '/api/v1/vendor/categories', auth: true, description: 'Vendor: list categories for store type (authVendor + requireApproved)' },
  { method: 'GET', path: '/api/v1/vendor/products', auth: true, description: 'Vendor: list products (authVendor + requireApproved); query: category, isAvailable, page, limit' },
  { method: 'GET', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: get product by id (403 if wrong vendor)' },
  { method: 'GET', path: '/api/v1/vendor/orders', auth: true, description: 'Vendor: list orders; query: status, page, limit' },
  { method: 'GET', path: '/api/v1/vendor/orders/:id', auth: true, description: 'Vendor: get order by id (403 if wrong vendor)' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/status', auth: true, description: 'Vendor: update order status (allowed transitions); body: status, note' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/reject', auth: true, description: 'Vendor: reject order (pending only); body: note' },
  { method: 'POST', path: '/api/v1/vendor/products', auth: true, description: 'Vendor: create product (multipart: name, price, category required; description, image optional); emits product:created' },
  { method: 'PATCH', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: update product (multipart, all optional); replace image if uploaded' },
  { method: 'PATCH', path: '/api/v1/vendor/products/:id/toggle', auth: true, description: 'Vendor: toggle isAvailable (Stock); emits product:toggled when set to false' },
  { method: 'DELETE', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: soft-delete product; emits product:deleted' },
  { method: 'GET', path: '/api/v1/admin/categories', auth: true, description: 'List categories (admin); query: type, isActive' },
  { method: 'POST', path: '/api/v1/admin/categories', auth: true, description: 'Create category (admin); multipart: name, type, description, sortOrder, icon (file)' },
  { method: 'PATCH', path: '/api/v1/admin/categories/reorder', auth: true, description: 'Reorder categories (admin); body: [{ id, sortOrder }, ...]' },
  { method: 'PATCH', path: '/api/v1/admin/categories/:id', auth: true, description: 'Update category (admin); multipart: name, type, description, sortOrder, isActive, icon (file)' },
  { method: 'PATCH', path: '/api/v1/admin/categories/:id/toggle', auth: true, description: 'Toggle category active (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/categories/:id', auth: true, description: 'Soft-delete category (admin); 409 if in use by vendors' },
  { method: 'GET', path: '/api/v1/app/categories', auth: false, description: 'List categories (app); query: type (food|grocery|pharmacy|fashion|retail)' },
  { method: 'GET', path: '/api/v1/app/categories/:slug/vendors', auth: false, description: 'List vendors in category by slug (app); query: sort, minRating, maxDeliveryTime, minPrice, maxPrice, page, limit' },
  { method: 'GET', path: '/api/v1/app/vendors', auth: false, description: 'List vendors (app); query: search, category, sort, minRating, maxDeliveryTime, minPrice, maxPrice, page, limit' },
  { method: 'GET', path: '/api/v1/app/vendors/:id', auth: false, description: 'Get vendor by id with products (app)' },
  { method: 'GET', path: '/api/v1/app/products/:id', auth: false, description: 'Get product by id (app); public' },
  { method: 'GET', path: '/api/v1/app/cart', auth: true, description: 'Get cart (customer); Bearer required' },
  { method: 'POST', path: '/api/v1/app/cart', auth: true, description: 'Set cart (customer); body: vendorId, items [{ productId, qty }]' },
  { method: 'PATCH', path: '/api/v1/app/cart/item', auth: true, description: 'Update cart item (customer); body: productId, qty (0 to remove)' },
  { method: 'DELETE', path: '/api/v1/app/cart', auth: true, description: 'Clear cart (customer)' },
  { method: 'GET', path: '/api/v1/app/customer/profile', auth: true, description: 'Get customer profile (fullName, phone, profileImage, points, totalOrders only)' },
  { method: 'PUT', path: '/api/v1/app/customer/profile', auth: true, description: 'Update customer profile (fullName, phone, profileImage only; multipart)' },
  { method: 'PUT', path: '/api/v1/app/customer/fcm-token', auth: true, description: 'Update FCM token (body: fcmToken)' },
  { method: 'GET', path: '/api/v1/app/customer/addresses', auth: true, description: 'Get addresses' },
  { method: 'POST', path: '/api/v1/app/customer/addresses', auth: true, description: 'Add address (body: addressLine1, saveAddressType, city, country; optional addressLine2, landmark, lat, lng, isDefault)' },
  { method: 'PUT', path: '/api/v1/app/customer/addresses/:id', auth: true, description: 'Update address by id (MongoDB address _id)' },
  { method: 'DELETE', path: '/api/v1/app/customer/addresses/:id', auth: true, description: 'Delete address by id (MongoDB address _id)' },
  { method: 'GET', path: '/api/v1/app/customer/order-history', auth: true, description: 'Customer order history (paginated)' },
  { method: 'DELETE', path: '/api/v1/app/customer/account', auth: true, description: 'Delete account (soft delete, invalidate tokens)' },
  { method: 'POST', path: '/api/v1/app/orders', auth: true, description: 'Place order (customer)' },
  { method: 'GET', path: '/api/v1/app/orders', auth: true, description: 'List my orders (customer)' },
  { method: 'GET', path: '/api/v1/app/orders/:id', auth: true, description: 'Get order (customer)' },
  { method: 'PATCH', path: '/api/v1/app/orders/:id/cancel', auth: true, description: 'Cancel order (customer)' },
  { method: 'POST', path: '/api/v1/app/orders/:id/rate', auth: true, description: 'Rate order (customer)' },
  { method: 'GET', path: '/api/v1/app/orders/:id/track', auth: true, description: 'Track order (customer)' },
  { method: 'GET', path: '/api/v1/app/driver/profile', auth: true, description: 'Get driver profile' },
  { method: 'PUT', path: '/api/v1/app/driver/profile', auth: true, description: 'Update driver profile' },
  { method: 'PUT', path: '/api/v1/app/driver/fcm-token', auth: true, description: 'Update FCM token (driver)' },
  { method: 'PATCH', path: '/api/v1/app/driver/online-status', auth: true, description: 'Update online status (driver)' },
  { method: 'PUT', path: '/api/v1/app/driver/location', auth: true, description: 'Update location (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/current-order', auth: true, description: 'Current order (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/earnings', auth: true, description: 'Earnings (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/delivery-history', auth: true, description: 'Delivery history (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/available', auth: true, description: 'Available orders (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/active', auth: true, description: 'Active order (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/history', auth: true, description: 'Delivery history list (driver)' },
  { method: 'POST', path: '/api/v1/app/driver/orders/:id/accept', auth: true, description: 'Accept order (driver)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/status', auth: true, description: 'Update order status (driver)' },
  { method: 'POST', path: '/api/v1/payment/initiate', auth: true, description: 'Initiate payment (customer)' },
  { method: 'GET', path: '/api/v1/payment/status/:reference', auth: true, description: 'Payment status' },
  { method: 'POST', path: '/api/v1/payment/refund', auth: true, description: 'Refund (admin)' },
  { method: 'POST', path: '/api/v1/payment/callback', auth: false, description: 'WifiPay webhook (no auth)' },
];

export function docsHandler(_req: Request, res: Response): void {
  res.json({
    version: 'v1',
    baseUrl: '/api/v1',
    routes: ROUTES,
  });
}
