import type { Request, Response } from 'express';

/** Machine-readable route map for API consumers (e.g. mobile). GET /api/docs */
export const ROUTES = [
  { method: 'GET', path: '/api/health', auth: false, description: 'Health check' },
  {
    method: 'GET',
    path: '/api/v1/test/socket/emit',
    auth: false,
    description:
      'Dev only (404 in production): broadcasts Socket.IO event `test:ping` to all connected clients — use to verify Postman Socket.IO without JWT or room join.',
  },
  {
    method: 'POST',
    path: '/api/v1/test/socket/emit',
    auth: false,
    description: 'Same as GET /test/socket/emit — dev-only `test:ping` broadcast.',
  },
  { method: 'GET', path: '/api/v1', auth: false, description: 'API v1 welcome' },
  { method: 'POST', path: '/api/v1/auth/admin/login', auth: false, description: 'Admin login (sets cookies)' },
  { method: 'POST', path: '/api/v1/auth/admin/refresh', auth: false, description: 'Admin refresh (cookie)' },
  { method: 'POST', path: '/api/v1/auth/admin/logout', auth: true, description: 'Admin logout' },
  { method: 'POST', path: '/api/v1/auth/customer/send-otp', auth: false, description: 'Customer: send phone OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/customer/verify-otp', auth: false, description: 'Customer: verify OTP (body: phone, otp); returns user, accessToken, refreshToken, expiresIn' },
  { method: 'POST', path: '/api/v1/auth/customer/resend-otp', auth: false, description: 'Customer: resend OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/customer/refresh', auth: false, description: 'Customer: refresh tokens (body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/customer/logout', auth: true, description: 'Customer: logout (optional body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/vendor/send-otp', auth: false, description: 'Vendor: send OTP to phone (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/vendor/verify-otp', auth: false, description: 'Vendor: verify OTP (body: phone, otp); returns accessToken, refreshToken, isNewVendor, onboardingStep' },
  { method: 'POST', path: '/api/v1/auth/vendor/resend-otp', auth: false, description: 'Vendor: resend OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/vendor/refresh', auth: false, description: 'Vendor: refresh tokens (body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/vendor/logout', auth: true, description: 'Vendor: logout (Bearer required; optional body: refreshToken, fcmToken)' },
  { method: 'POST', path: '/api/v1/auth/driver/send-otp', auth: false, description: 'Driver: send OTP (body: phone); phone-only auth; rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/driver/verify-otp', auth: false, description: 'Driver: verify OTP (body: phone, otp); returns accessToken, refreshToken, isNewDriver, approvalStatus' },
  { method: 'POST', path: '/api/v1/auth/driver/resend-otp', auth: false, description: 'Driver: resend OTP (body: phone); rate limit 5/hour per phone' },
  { method: 'POST', path: '/api/v1/auth/driver/refresh', auth: false, description: 'Driver: refresh tokens (body: refreshToken)' },
  { method: 'POST', path: '/api/v1/auth/driver/logout', auth: true, description: 'Driver: logout (Bearer required; optional body: refreshToken, fcmToken)' },
  { method: 'GET', path: '/api/v1/driver/setup/status', auth: true, description: 'Driver setup: status (approvalStatus, name, profileImage)' },
  { method: 'PATCH', path: '/api/v1/driver/setup/profile-info', auth: true, description: 'Driver setup profile info (multipart: name required; phone optional; profileImage optional max 10MB jpeg/png/webp; same phone allowed)' },
  { method: 'GET', path: '/api/v1/driver/kyc/status', auth: true, description: 'Driver KYC + profile summary (name, phone, profileImage, vehicleType, vehicleNumber, approvalStatus, kycStatus, kycRejectionReason, kycSubmittedAt, kycDocuments)' },
  {
    method: 'POST',
    path: '/api/v1/driver/kyc/upload',
    auth: true,
    description:
      'Driver KYC: upload documents + vehicle details (multipart: vehicleType, vehicleNumber, driversLicense 1 file, nationalId ≤10, vehiclePhotos ≤10; jpg/png/pdf, 5MB each); sets pending; Socket.IO driver:kyc_submitted → admin room { driverId, name, phone, submittedAt }',
  },
  {
    method: 'PATCH',
    path: '/api/v1/driver/kyc/resubmit',
    auth: true,
    description: 'Driver KYC: reset after rejection to not_submitted (re-upload via POST /upload); 200 → client clears file state',
  },
  {
    method: 'GET',
    path: '/api/v1/driver/profile',
    auth: true,
    description:
      'Driver self profile: full logged-in driver document (KYC, location, wallet, bankAccount, etc.); secrets omitted (password, OTP, refresh token).',
  },
  { method: 'PATCH', path: '/api/v1/driver/profile', auth: true, description: 'Driver self profile: update profile (multipart optional: name, phone, profileImage max 10MB, vehicleType, vehicleNumber)' },
  { method: 'POST', path: '/api/v1/driver/profile/fcm-token', auth: true, description: 'Driver self profile: register FCM token (body: token required, device optional; max 5)' },
  { method: 'DELETE', path: '/api/v1/driver/profile/fcm-token', auth: true, description: 'Driver self profile: remove FCM token (body: token required)' },
  { method: 'PATCH', path: '/api/v1/driver/profile/status', auth: true, description: "Driver self profile: set status online/offline (body: { status: 'online'|'offline' }); approved only; emits driver:status_changed to admin room" },
  {
    method: 'PATCH',
    path: '/api/v1/driver/location',
    auth: true,
    description:
      'Driver live GPS update — body { lat, lng, heading? }; persists location and emits socket `driver:location` to customer & vendor rooms when the driver has an active order (preparing|ready|picked_up|on_the_way). Bearer required. Complements socket event `driver:location_update`.',
  },
  {
    method: 'GET',
    path: '/api/v1/driver/notifications',
    auth: true,
    description:
      'Driver in-app notifications — paginated list (query: page, limit, unreadOnly=true). Response data: notifications, unreadCount, pagination.',
  },
  {
    method: 'PATCH',
    path: '/api/v1/driver/notifications/read-all',
    auth: true,
    description: 'Driver notifications: mark all as read for the authenticated driver; returns data.updated (MongoDB modified count).',
  },
  {
    method: 'GET',
    path: '/api/v1/driver/earnings',
    auth: true,
    description:
      'Driver earnings dashboard (same payload as GET /api/v1/app/driver/earnings): `withdrawFunds` null; `lifetime` (totalEarnings, totalDeliveries, totalHoursWorked); `periods.daily|weekly|monthly` each with totalEarnings, dateRangeLabel, earningsChangePercent/Label, totalDeliveries, totalHoursWorked, performanceGraph (7-day bars for weekly only; null for daily/monthly), recentDeliveries. Bearer from /auth/driver/verify-otp; authDriver.',
  },
  {
    method: 'GET',
    path: '/api/v1/driver/dashboard',
    auth: true,
    description:
      'Driver home dashboard (Figma-aligned): driverProfile (name, tierLabel, profileImageUrl, isOnline), todaysEarningsCard (periodLabel, totalEarnings, orderCount, hoursWorked, tipsAmount), totalEarningsCard (label Total Earnings, amount = lifetime delivered earnings — not walletBalance, cashOutCtaLabel, cashOutAvailable, withdrawFunds null), newOrdersCount, activeOrders (figmaDisplay, pickup/dropoff locations, estTimeLabel, distances, orderCard same as GET /driver/orders/active), map (openMapButtonLabel, previewUrl, center). Same auth as /driver/earnings.',
  },
  {
    method: 'GET',
    path: '/api/v1/driver/orders/:id/detail',
    auth: true,
    description:
      'Driver delivery order detail — map, pickup, dropoff, line items, earnings; only if this driver is assigned to the order or was targeted for assignment (broadcast/notify list).',
  },
  { method: 'GET', path: '/api/v1/vendor/onboarding/status', auth: true, description: 'Vendor onboarding: get status (onboardingStep, approvalStatus, submittedAt, name)' },
  { method: 'PATCH', path: '/api/v1/vendor/onboarding/business-info', auth: true, description: 'Vendor onboarding Step 2: business info (multipart: storeName, description, operatingHours JSON, logo)' },
  { method: 'PATCH', path: '/api/v1/vendor/onboarding/address', auth: true, description: 'Vendor onboarding Step 3: address (addressLine1, addressLine2, landmark, lat, lng, addressLabel)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/kyc-documents', auth: true, description: 'Vendor onboarding Step 5: KYC (multipart: businessRegistration, identityDocument, healthSafetyLicense optional)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/submit', auth: true, description: 'Vendor onboarding Step 6: submit application (422 if steps incomplete)' },
  { method: 'POST', path: '/api/v1/vendor/onboarding/resubmit', auth: true, description: 'Vendor onboarding: resubmit after rejection; resets approvalStatus=none, step=4, emits vendor:new_submission' },
  { method: 'GET', path: '/api/v1/admin/users', auth: true, description: 'List users (admin)' },
  { method: 'POST', path: '/api/v1/admin/users', auth: true, description: 'Create user (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/export/csv', auth: true, description: 'Export users CSV (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/:id', auth: true, description: 'Get user (admin)' },
  { method: 'PUT', path: '/api/v1/admin/users/:id', auth: true, description: 'Update user (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/users/:id', auth: true, description: 'Delete user (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/users/:id/status', auth: true, description: 'Patch user status (admin)' },
  { method: 'GET', path: '/api/v1/admin/users/:id/orders', auth: true, description: 'Get user orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/customers', auth: true, description: 'List customers (admin)' },
  { method: 'GET', path: '/api/v1/admin/customers/:id', auth: true, description: 'Get customer (admin)' },
  { method: 'POST', path: '/api/v1/admin/customers', auth: true, description: 'Create customer (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/customers/:id', auth: true, description: 'Update customer (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/customers/:id/block', auth: true, description: 'Block/unblock customer (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/customers/:id', auth: true, description: 'Delete customer (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/stats/pending-count', auth: true, description: 'Pending drivers count (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers', auth: true, description: 'List drivers (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Get driver (admin); includes kycStatus, kycRejectionReason, kycSubmittedAt, kycDocuments' },
  { method: 'PUT', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Update driver (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/drivers/:id', auth: true, description: 'Delete driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/approve', auth: true, description: 'Approve driver (admin); if kycStatus was pending, sets KYC approved + socket driver:kyc_approved + FCM' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/reject', auth: true, description: 'Reject driver (admin); body reason (min 10 chars), optional kycRejectionReason; sets kyc rejected + socket driver:kyc_rejected + FCM' },
  { method: 'PATCH', path: '/api/v1/admin/drivers/:id/status', auth: true, description: 'Update driver status (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id/orders', auth: true, description: 'Driver orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/drivers/:id/location', auth: true, description: 'Driver location (admin)' },
  { method: 'GET', path: '/api/v1/admin/app-settings', auth: true, description: 'Get app settings (admin): deliveryFee, taxPercent, defaultCurrency, defaultTimezone, serviceZones' },
  { method: 'PATCH', path: '/api/v1/admin/app-settings', auth: true, description: 'Update app settings (admin): deliveryFee, taxPercent; optional defaultCurrency (ISO 4217), defaultTimezone (IANA), serviceZones (string[])' },
  { method: 'GET', path: '/api/v1/admin/orders/stats/summary', auth: true, description: 'Orders stats summary (admin)' },
  { method: 'GET', path: '/api/v1/admin/orders', auth: true, description: 'List orders (admin)' },
  { method: 'GET', path: '/api/v1/admin/orders/:id', auth: true, description: 'Get order (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/status', auth: true, description: 'Update order status (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/cancel', auth: true, description: 'Cancel order (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/assign-driver', auth: true, description: 'Assign driver (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/orders/:id/driver', auth: true, description: 'Assign driver (admin); body: driverId' },
  { method: 'GET', path: '/api/v1/admin/transactions/stats/revenue', auth: true, description: 'Revenue stats (admin)' },
  { method: 'GET', path: '/api/v1/admin/transactions', auth: true, description: 'List transactions (admin)' },
  { method: 'GET', path: '/api/v1/admin/transactions/:id', auth: true, description: 'Get transaction (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors', auth: true, description: 'List vendors (admin); query: approvalStatus, search, status; response meta: pendingCount' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Get vendor (admin)' },
  { method: 'POST', path: '/api/v1/admin/vendors', auth: true, description: 'Create vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Update vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/block', auth: true, description: 'Block/unblock vendor (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/approve', auth: true, description: 'Approve vendor (admin); vendor must be pending; emits vendor:approved, FCM to vendor' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/reject', auth: true, description: 'Reject vendor (admin); body: { reason } min 10 chars; emits vendor:rejected, FCM to vendor' },
  { method: 'DELETE', path: '/api/v1/admin/vendors/:id', auth: true, description: 'Delete vendor (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id/menu-items', auth: true, description: 'List vendor menu items (admin)' },
  { method: 'POST', path: '/api/v1/admin/vendors/:id/menu-items', auth: true, description: 'Create menu item (admin)' },
  { method: 'PATCH', path: '/api/v1/admin/vendors/:id/menu-items/:itemId', auth: true, description: 'Update menu item (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/vendors/:id/menu-items/:itemId', auth: true, description: 'Delete menu item (admin)' },
  { method: 'GET', path: '/api/v1/admin/vendors/:id/products', auth: true, description: 'List vendor products (admin, Phase 4); query: page, limit, category, isAvailable' },
  { method: 'GET', path: '/api/v1/vendor/categories', auth: true, description: 'Vendor: list categories for store type (authVendor + requireApproved)' },
  { method: 'GET', path: '/api/v1/vendor/products', auth: true, description: 'Vendor: list products (authVendor + requireApproved); query: category, isAvailable, page, limit' },
  { method: 'GET', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: get product by id (403 if wrong vendor)' },
  {
    method: 'GET',
    path: '/api/v1/vendor/dashboard',
    auth: true,
    description:
      'Vendor app dashboard: store + storeId, today earnings (paid delivered, vendor timezone), vs-yesterday %, rating, newOrdersCount, embedded newOrders[] and activeOrders[] (same order documents + remainingTime as /vendor/orders/new and in-kitchen pipeline including ready; capped at 200 each with newOrdersTruncated/activeOrdersTruncated when more exist), activeOrdersCount, wallet, menu summary. Use GET /vendor/orders/new|current with page for full pagination when truncated.',
  },
  {
    method: 'GET',
    path: '/api/v1/vendor/wallet',
    auth: true,
    description:
      'Vendor wallet / earnings (single GET): `overview` (summary + recentOrders), `revenueAnalytics` (periodRevenue, graphs.daily/monthly null, weekly bars, totals, changeByPeriod, recentOrders), `orderBuckets` (queued=pending|vendor_notified|placed, active=in-progress, delivered=delivered; max 50 each, totalAmount = sum order totals). Earnings use effective vendor revenue on delivered orders (stored vendorShare when positive, else same formula as order placement / PLATFORM_COMMISSION_RATE). COD; no payout fields.',
  },
  { method: 'GET', path: '/api/v1/vendor/orders', auth: true, description: 'Vendor: list orders; query: status, page, limit' },
  { method: 'GET', path: '/api/v1/vendor/orders/new', auth: true, description: 'Vendor: list NEW orders (status=vendor_notified); includes remainingTime; query: page, limit' },
  { method: 'GET', path: '/api/v1/vendor/orders/current', auth: true, description: 'Vendor: list CURRENT orders (accepted, preparing, picked_up, on_the_way); query: page, limit' },
  { method: 'GET', path: '/api/v1/vendor/orders/completed', auth: true, description: 'Vendor: list COMPLETED orders (delivered, cancelled); query: page, limit' },
  { method: 'GET', path: '/api/v1/vendor/orders/:id', auth: true, description: 'Vendor: get order by id (403 if wrong vendor)' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/status', auth: true, description: 'Vendor: update order status (allowed transitions); body: status, note' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/accept', auth: true, description: 'Vendor: accept order (vendor_notified only, before deadline)' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/ready', auth: true, description: 'Vendor: mark order ready for pickup (preparing -> ready)' },
  { method: 'PATCH', path: '/api/v1/vendor/orders/:id/reject', auth: true, description: 'Vendor: reject order (vendor_notified only, before deadline); body: reason' },
  {
    method: 'GET',
    path: '/api/v1/vendor/test/nearby-drivers',
    auth: true,
    description:
      'TEMPORARY (remove later): same nearby-driver list as order accept — query radiusKm (1–50, default 5); requires vendor address lat/lng.',
  },
  { method: 'GET', path: '/api/v1/vendor/profile', auth: true, description: 'Vendor self profile (authVendor + requireApproved)' },
  { method: 'PATCH', path: '/api/v1/vendor/profile', auth: true, description: 'Vendor update profile (multipart, all optional): name, phone (unique), logo (10MB), coverImage (10MB), deliveryTime, minimumOrder, address JSON' },
  { method: 'PATCH', path: '/api/v1/vendor/profile/toggle', auth: true, description: 'Vendor: toggle isOpen (manual override); emits vendor:availability_changed to admin' },
  { method: 'PATCH', path: '/api/v1/vendor/profile/operating-hours', auth: true, description: 'Vendor: replace operatingHours (JSON body); requires all 7 days; 422 on validation errors' },
  { method: 'POST', path: '/api/v1/vendor/profile/fcm-token', auth: true, description: 'Vendor self profile: register FCM token (body: token required, device optional; max 5)' },
  { method: 'DELETE', path: '/api/v1/vendor/profile/fcm-token', auth: true, description: 'Vendor self profile: remove FCM token (body: token required)' },
  { method: 'POST', path: '/api/v1/vendor/products', auth: true, description: 'Vendor: create product (multipart: name, price, category required; description, image optional); emits product:created' },
  { method: 'PATCH', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: update product (multipart, all optional); replace image if uploaded' },
  { method: 'PATCH', path: '/api/v1/vendor/products/:id/toggle', auth: true, description: 'Vendor: toggle isAvailable (Stock); emits product:toggled when set to false' },
  { method: 'DELETE', path: '/api/v1/vendor/products/:id', auth: true, description: 'Vendor: soft-delete product; emits product:deleted' },
  { method: 'GET', path: '/api/v1/admin/categories', auth: true, description: 'List categories (admin); query: type, isActive' },
  { method: 'POST', path: '/api/v1/admin/categories', auth: true, description: 'Create category (admin); multipart: name, type, description, sortOrder, icon (file)' },
  { method: 'PATCH', path: '/api/v1/admin/categories/reorder', auth: true, description: 'Reorder categories (admin); body: [{ id, sortOrder }, ...]' },
  { method: 'PATCH', path: '/api/v1/admin/categories/:id', auth: true, description: 'Update category (admin); multipart: name, type, description, sortOrder, isActive, icon (file)' },
  { method: 'PATCH', path: '/api/v1/admin/categories/:id/toggle', auth: true, description: 'Toggle category active (admin)' },
  { method: 'DELETE', path: '/api/v1/admin/categories/:id', auth: true, description: 'Soft-delete category (admin); 409 if in use by vendors' },
  { method: 'GET', path: '/api/v1/app/categories', auth: false, description: 'List categories (app); query: type (food|grocery|pharmacy|fashion|retail)' },
  { method: 'GET', path: '/api/v1/app/categories/:slug/vendors', auth: false, description: 'List vendors in category by slug (app); query: sort, minRating, maxDeliveryTime, minPrice, maxPrice, page, limit' },
  { method: 'GET', path: '/api/v1/app/vendors', auth: false, description: 'List vendors (app); query: search, category (ObjectId), type (food|grocery|pharmacy|fashion|retail), sort, minRating, maxDeliveryTime, minPrice, maxPrice, page, limit; optional customerLat+customerLng for ETA/distance from Google Distance Matrix' },
  { method: 'GET', path: '/api/v1/app/vendors/recommended', auth: false, description: 'Recommended vendors (app): higher-rated first; query category=all|food|grocery|pharmacy|fashion|retail or category ObjectId; if no rated vendors, fallback to 3-4 active available vendors' },
  { method: 'GET', path: '/api/v1/app/vendors/:id', auth: false, description: 'Get vendor by id with products (app)' },
  { method: 'GET', path: '/api/v1/app/vendors/:id/ratings', auth: false, description: 'Get vendor ratings list with averageRating and totalRatings' },
  { method: 'POST', path: '/api/v1/app/vendors/:id/ratings', auth: true, description: 'Rate vendor from delivered order; body: orderId, rating (1-5), comment; one rating per order' },
  { method: 'GET', path: '/api/v1/app/products/:id', auth: false, description: 'Get product by id (app); public' },
  { method: 'GET', path: '/api/v1/app/cart', auth: true, description: 'Get cart (customer); includes deliveryFee, taxPercent, taxAmount, grandTotal; Bearer required' },
  { method: 'POST', path: '/api/v1/app/cart', auth: true, description: 'Set cart (customer); body: vendorId, items [{ productId, qty }]' },
  { method: 'PATCH', path: '/api/v1/app/cart/item', auth: true, description: 'Update cart item (customer); body: productId, qty (0 to remove)' },
  { method: 'DELETE', path: '/api/v1/app/cart', auth: true, description: 'Clear cart (customer)' },
  { method: 'GET', path: '/api/v1/app/customer/profile', auth: true, description: 'Get customer profile (fullName, phone, profileImage, points, totalOrders only)' },
  { method: 'PUT', path: '/api/v1/app/customer/profile', auth: true, description: 'Update customer profile (fullName, phone, profileImage only; multipart; profileImage max 10MB)' },
  { method: 'PUT', path: '/api/v1/app/customer/fcm-token', auth: true, description: 'Update FCM token (body: fcmToken)' },
  {
    method: 'GET',
    path: '/api/v1/app/customer/addresses',
    auth: true,
    description:
      'Get addresses; optional query filters: custLat, custLong. If both are provided, returns only addresses within 40km of those coordinates; if omitted, returns all saved addresses. data.addresses each has preferred boolean; first saved address is preferred; ordering or PUT can change preferred.',
  },
  { method: 'POST', path: '/api/v1/app/customer/addresses', auth: true, description: 'Add address; first save is home + preferred; further addresses are not preferred until chosen via PUT or order' },
  { method: 'PUT', path: '/api/v1/app/customer/addresses/:id', auth: true, description: 'Update address by id; this address becomes preferred (or send preferred true only)' },
  { method: 'DELETE', path: '/api/v1/app/customer/addresses/:id', auth: true, description: 'Delete address by id (MongoDB address _id)' },
  { method: 'GET', path: '/api/v1/app/customer/order-history', auth: true, description: 'Customer order history (paginated)' },
  { method: 'PUT', path: '/api/v1/app/customer/wishlist', auth: true, description: 'Update wishlist (like/dislike vendor); body: vendorId, action' },
  { method: 'GET', path: '/api/v1/app/customer/wishlist', auth: true, description: 'Get customer wishlist vendors with rating fields' },
  { method: 'DELETE', path: '/api/v1/app/customer/account', auth: true, description: 'Delete account (soft delete, invalidate tokens)' },
  { method: 'POST', path: '/api/v1/app/orders', auth: true, description: 'Place order (customer); cart-based with deliveryAddressId preferred, returns items, totals, OTP, displayOrderId' },
  { method: 'GET', path: '/api/v1/app/orders', auth: true, description: 'List my orders (customer)' },
  { method: 'GET', path: '/api/v1/app/orders/:id', auth: true, description: 'Get order (customer)' },
  { method: 'GET', path: '/api/v1/app/orders/:id/chat', auth: true, description: 'Get customer chat history for order; query: page, limit' },
  { method: 'POST', path: '/api/v1/app/orders/:id/chat', auth: true, description: 'Send customer chat message for order; body: message' },
  { method: 'PATCH', path: '/api/v1/app/orders/:id/cancel', auth: true, description: 'Cancel order (customer)' },
  { method: 'POST', path: '/api/v1/app/orders/:id/rate', auth: true, description: 'Rate order (customer)' },
  { method: 'GET', path: '/api/v1/app/orders/:id/track', auth: true, description: 'Track order (customer)' },
  { method: 'GET', path: '/api/v1/app/driver/profile', auth: true, description: 'Get driver profile' },
  { method: 'PUT', path: '/api/v1/app/driver/profile', auth: true, description: 'Update driver profile' },
  { method: 'PUT', path: '/api/v1/app/driver/fcm-token', auth: true, description: 'Update FCM token (driver)' },
  { method: 'PATCH', path: '/api/v1/app/driver/online-status', auth: true, description: 'Update online status (driver)' },
  { method: 'PUT', path: '/api/v1/app/driver/location', auth: true, description: 'Update location (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/current-order', auth: true, description: 'Current order (driver)' },
  {
    method: 'GET',
    path: '/api/v1/app/driver/earnings',
    auth: true,
    description:
      'Driver earnings dashboard — identical to GET /api/v1/driver/earnings (JWT role driver via authenticateJWT). See /driver/earnings for payload shape.',
  },
  {
    method: 'GET',
    path: '/api/v1/app/driver/dashboard',
    auth: true,
    description:
      'Driver home dashboard — same payload as GET /api/v1/driver/dashboard (JWT role driver via authenticateJWT).',
  },
  { method: 'GET', path: '/api/v1/app/driver/delivery-history', auth: true, description: 'Delivery history (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/available', auth: true, description: 'Available orders (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/new', auth: true, description: 'New orders tab (driver); query: page, limit' },
  { method: 'GET', path: '/api/v1/app/driver/orders/active', auth: true, description: 'Active order (driver)' },
  { method: 'GET', path: '/api/v1/app/driver/orders/completed', auth: true, description: 'Completed orders tab (driver); query: page, limit' },
  { method: 'GET', path: '/api/v1/app/driver/orders/history', auth: true, description: 'Delivery history list (driver)' },
  { method: 'POST', path: '/api/v1/app/driver/orders/:id/accept', auth: true, description: 'Driver: accept assignment (accepted -> preparing)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/accept', auth: true, description: 'Driver: accept assignment (accepted -> preparing)' },
  { method: 'POST', path: '/api/v1/app/driver/orders/:id/reject', auth: true, description: 'Driver: reject assignment (keeps order open for others)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/pickup', auth: true, description: 'Driver: pickup order (ready -> picked_up)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/enroute', auth: true, description: 'Driver: mark enroute (picked_up -> on_the_way)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/deliver', auth: true, description: 'Driver: deliver order with OTP (on_the_way -> delivered)' },
  { method: 'PATCH', path: '/api/v1/app/driver/orders/:id/status', auth: true, description: 'Update order status (driver)' },
  { method: 'GET', path: '/api/v1/driver/orders/available', auth: true, description: 'Available orders (driver)' },
  { method: 'GET', path: '/api/v1/driver/orders/new', auth: true, description: 'New orders tab (driver); query: page, limit' },
  { method: 'GET', path: '/api/v1/driver/orders/active', auth: true, description: 'Active order (driver)' },
  { method: 'GET', path: '/api/v1/driver/orders/completed', auth: true, description: 'Completed orders tab (driver); query: page, limit' },
  { method: 'GET', path: '/api/v1/driver/orders/history', auth: true, description: 'Delivery history list (driver)' },
  { method: 'POST', path: '/api/v1/driver/orders/:id/accept', auth: true, description: 'Driver: accept assignment (accepted -> preparing)' },
  { method: 'PATCH', path: '/api/v1/driver/orders/:id/accept', auth: true, description: 'Driver: accept assignment (accepted -> preparing)' },
  { method: 'POST', path: '/api/v1/driver/orders/:id/reject', auth: true, description: 'Driver: reject assignment (keeps order open for others)' },
  { method: 'PATCH', path: '/api/v1/driver/orders/:id/pickup', auth: true, description: 'Driver: pickup order (ready -> picked_up)' },
  { method: 'PATCH', path: '/api/v1/driver/orders/:id/enroute', auth: true, description: 'Driver: mark enroute (picked_up -> on_the_way)' },
  { method: 'PATCH', path: '/api/v1/driver/orders/:id/deliver', auth: true, description: 'Driver: deliver order with OTP (on_the_way -> delivered)' },
  { method: 'GET', path: '/api/v1/driver/orders/:id/chat', auth: true, description: 'Get driver chat history for assigned order; query: page, limit' },
  { method: 'POST', path: '/api/v1/driver/orders/:id/chat', auth: true, description: 'Send driver chat message for assigned order; body: message' },
  { method: 'POST', path: '/api/v1/payment/initiate', auth: true, description: 'Initiate payment (customer)' },
  { method: 'GET', path: '/api/v1/payment/status/:reference', auth: true, description: 'Payment status' },
  { method: 'POST', path: '/api/v1/payment/refund', auth: true, description: 'Refund (admin)' },
  { method: 'POST', path: '/api/v1/payment/callback', auth: false, description: 'WifiPay webhook (no auth)' },
];

export function docsHandler(_req: Request, res: Response): void {
  res.json({
    version: 'v1',
    baseUrl: '/api/v1',
    routes: ROUTES,
  });
}
